export const GETALL_CLASSROOM = "GETALL_CLASSROOM";
export const GETONE_CLASSROOM = "GETONE_CLASSROOM";
export const CREATE_CLASSROOM = "CREATE_CLASSROOM";
export const UPDATE_CLASSROOM = "UPDATE_CLASSROOM";
export const UPDATESTATUS_CLASSROOM = "UPDATESTATUS_CLASSROOM";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";

export const GETALL_STUDENT = "GETALL_STUDENT";
export const GETONE_STUDENT = "GETONE_STUDENT";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const UPDATESTATUS_STUDENT = "UPDATESTATUS_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";

export const GETALL_SUBJECT = "GETALL_SUBJECT";
export const GETONE_SUBJECT = "GETONE_SUBJECT";
export const CREATE_SUBJECT = "CREATE_SUBJECT";
export const UPDATE_SUBJECT = "UPDATE_SUBJECT";
export const UPDATESTATUS_SUBJECT = "UPDATESTATUS_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";

export const GETALL_TEACHER = "GETALL_TEACHER";
export const GETONE_TEACHER = "GETONE_TEACHER";
export const CREATE_TEACHER = "CREATE_TEACHER";
export const UPDATE_TEACHER = "UPDATE_TEACHER";
export const UPDATESTATUS_TEACHER = "UPDATESTATUS_TEACHER";
export const DELETE_TEACHER = "DELETE_TEACHER";